language: python
python:
  - "3.6"
before_install:
  - sudo apt-get install graphviz
  - pwd
  - pip install future requests pygraphviz
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      pip install functools32;
    fi
  - git clone https://github.com/sorgerlab/indra.git
script:
  - pwd
  - echo $TRAVIS_BUILD_DIR
  - export PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/indra
  - python check_references.py
  - python export/relations_graph.py
  # test if exports have been updated
  # bel_resources must be installed to generate belns exports
  # generate exports then take git diff and look only at lines that changed
  # lines containing date, timestamp, or version should be ignored
  - pip install bel_resources
  - python export/obo.py
  - python export/hgnc_ids.py
  - python export/belns.py
  - export belns_diff=$(git diff -U0 export/famplex.belns | egrep "^[\+-][^\+-]")
  - export belns=$(echo "$belns_diff" | egrep -v "^[\+-](VersionString|CreatedDateTime)")
  - export obo_diff=$(git diff -U0 export/famplex.obo | egrep "^[\+-][^\+-]")
  - export obo=$(echo "$obo_diff" | egrep -v "^[\+-]date")
  - export hgnc=$(git diff -U0 export/hgnc_symbol_map.csv | egrep "^[\+-][^\+-]")
  - if [[ ! -z $belns ]] || [[ ! -z $obo ]] || [[ ! -z $hgnc ]]; then
      echo "FAIL exports have not been updated";
      exit 1;
    fi
